<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Dkplus\Test\Controller\Setup\MvcEvent'                      => __DIR__ . '/lib/DkplusTest/Controller/Setup/MvcEvent.php',
    'DkplusTest\Controller\Setup\MvcEventInterface'              => __DIR__ . '/lib/DkplusTest/Controller/Setup/MvcEventInterface.php',
    'Dkplus\Test\Controller\Setup\PhpEnvironmentRequestResponse' => __DIR__ . '/lib/DkplusTest/Controller/Setup/PhpEnvironmentRequestResponse.php',
    'Dkplus\Test\Controller\Setup\Plugin\AbstractPlugin'         => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/AbstractPlugin.php',
    'Dkplus\Test\Controller\Setup\Plugin\FlashMessenger'         => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/FlashMessenger.php',
    'Dkplus\Test\Controller\Setup\Plugin\Forward'                => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/Forward.php',
    'Dkplus\Test\Controller\Setup\Plugin\Layout'                 => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/Layout.php',
    'Dkplus\Test\Controller\Setup\Plugin\Redirect'               => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/Redirect.php',
    'Dkplus\Test\Controller\Setup\Plugin\Url'                    => __DIR__ . '/lib/DkplusTest/Controller/Setup/Plugin/Url.php',
    'Dkplus\Test\Controller\Setup\PluginManager'                 => __DIR__ . '/lib/DkplusTest/Controller/Setup/PluginManager.php',
    'Dkplus\Test\Controller\Setup\PluginManagerInterface'        => __DIR__ . '/lib/DkplusTest/Controller/Setup/PluginManagerInterface.php',
    'Dkplus\Test\Controller\Setup\RequestResponseInterface'      => __DIR__ . '/lib/DkplusTest/Controller/Setup/RequestResponseInterface.php',
    'DkplusTest\Controller\Setup\SetupInterface'                 => __DIR__ . '/lib/DkplusTest/Controller/Setup/SetupInterface.php',
    'Dkplus\Test\Controller\TestCase'                            => __DIR__ . '/lib/DkplusTest/Controller/TestCase.php',
    'DkplusTest\TestCase'                                        => __DIR__ . '/lib/DkplusTest/TestCase.php',
);